server:
  port: 7003
spring:
  application:
    name: eureka-consumer1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server2:7001/eureka/
  instance:
    hostname: localhost
